#!/usr/bin/env node
/*
 * Builds supabase/seed.sql: a test master "test-studio" with the demo's
 * photos and texts, real services, working hours with a lunch break,
 * one day off and a few clients and bookings around today.
 *
 *   node tools/make-seed.js [owner@email]
 *
 * The email (default owner@example.com) is only stored for your records:
 * the dashboard account is linked by owner_id (see README, "Вариант B").
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const demo = JSON.parse(fs.readFileSync(path.join(ROOT, 'masters', 'demo.json'), 'utf8'));
const ownerEmail = process.argv[2] || 'owner@example.com';

const MASTER_ID = '7e570000-0000-4000-8000-000000000001';
const svcId = i => `7e570000-0000-4000-8000-1000000000${String(i + 1).padStart(2, '0')}`;

const minutes = v => {
  const s = String(v || '');
  const h = s.match(/(\d+(?:\.\d+)?)\s*h/i);
  const m = s.match(/(\d+)\s*m/i);
  return (h ? Math.round(+h[1] * 60) : 0) + (m ? +m[1] : 0) || 60;
};

// only what a real master sets herself in the dashboard — no demo numbers,
// reviews, stories, promo or loyalty progress (those stay in the demo JSON)
const OWN = ['tagline', 'city', 'address', 'parking', 'phone', 'instagram', 'heroPhoto', 'heroVideo', 'avatar',
  'policies', 'prep', 'aftercare', 'faq', 'splashStyle', 'splashEmoji'];
const settings = {};
OWN.forEach(k => { if (demo[k] != null) settings[k] = demo[k]; });
settings.tagline = 'Lashes & brows — book online in a minute';
let settingsJson = JSON.stringify(settings);
// gallery / owner demo point at services by id → the new uuids
demo.services.forEach((s, i) => { settingsJson = settingsJson.split(`"${s.id}"`).join(`"${svcId(i)}"`); });

const q = s => `'${String(s).replace(/'/g, "''")}'`;
const services = demo.services.map((s, i) => `  (${q(svcId(i))}, ${q(MASTER_ID)}, ${q(s.category)}, ${q(s.title)}, ${q(s.description || '')},
   ${'ARRAY[' + (s.includes || []).map(q).join(', ') + ']::text[]'}, ${minutes(s.duration)}, ${s.category === 'Lashes' ? 15 : 10},
   ${+s.price || 0}, ${/full set/i.test(s.title) ? 30 : 0}, ${q(s.photo || '')}, ${i})`).join(',\n');

const sql = `-- Generated by tools/make-seed.js — a test master to try the real booking flow.
-- Open the app with ?m=test-studio. Sign in to the dashboard as ${ownerEmail}.

insert into public.masters (id, slug, name, owner_email, timezone, style, accent, settings, booking_engine,
                            auto_confirm, min_notice_hours, max_days_ahead, cancel_window_hours, slot_step_min)
values (${q(MASTER_ID)}, 'test-studio', 'Test Studio', ${q(ownerEmail)}, 'America/New_York', 'noir', '#F4A6B8',
        $settings$${settingsJson}$settings$::jsonb, 'builtin', true, 2, 60, 24, 30)
on conflict (slug) do nothing;

insert into public.services (id, master_id, category, name, description, includes, duration_min, buffer_min,
                             price, deposit, photo, sort)
values
${services}
on conflict (id) do nothing;

-- Mon–Fri 9–1 and 2–7 (lunch break), Sat 10–4, Sunday closed
insert into public.working_hours (master_id, weekday, start_time, end_time)
select ${q(MASTER_ID)}::uuid, d, t.s, t.e
  from generate_series(1, 5) d, (values (time '09:00', time '13:00'), (time '14:00', time '19:00')) t(s, e)
union all
select ${q(MASTER_ID)}::uuid, 6, time '10:00', time '16:00';

-- A morning off in ten days
insert into public.time_off (master_id, start_at, end_at, reason)
select ${q(MASTER_ID)}::uuid,
       (((now() at time zone 'America/New_York')::date + 10) + time '09:00') at time zone 'America/New_York',
       (((now() at time zone 'America/New_York')::date + 10) + time '13:00') at time zone 'America/New_York',
       'Dentist';

-- A few clients and bookings around today (past ones are completed)
insert into public.clients (id, master_id, name, phone, email, notes)
values
  ('7e570000-0000-4000-8000-200000000001', ${q(MASTER_ID)}, 'Jasmine R.', '+14045550101', 'jasmine@example.com', 'Prefers a natural, wispy look. Sensitive eyes — use the gentle remover.'),
  ('7e570000-0000-4000-8000-200000000002', ${q(MASTER_ID)}, 'Taylor M.', '+14045550102', null, ''),
  ('7e570000-0000-4000-8000-200000000003', ${q(MASTER_ID)}, 'Brianna K.', '+14045550103', 'bri@example.com', 'Always 5 min early.')
on conflict do nothing;

with base as (select (now() at time zone 'America/New_York')::date as today),
plan(client, svc, day, at, status) as (values
  ('7e570000-0000-4000-8000-200000000001'::uuid, ${q(svcId(1))}::uuid, -14, time '10:00', 'completed'),
  ('7e570000-0000-4000-8000-200000000001'::uuid, ${q(svcId(6))}::uuid,  -1, time '15:00', 'completed'),
  ('7e570000-0000-4000-8000-200000000002'::uuid, ${q(svcId(0))}::uuid,  -7, time '11:00', 'no_show'),
  ('7e570000-0000-4000-8000-200000000003'::uuid, ${q(svcId(4))}::uuid,   1, time '09:00', 'confirmed'),
  ('7e570000-0000-4000-8000-200000000002'::uuid, ${q(svcId(3))}::uuid,   1, time '14:00', 'pending'),
  ('7e570000-0000-4000-8000-200000000001'::uuid, ${q(svcId(2))}::uuid,   3, time '10:00', 'confirmed')
)
insert into public.bookings (master_id, service_id, client_id, start_at, end_at, buffer_end_at, status, price,
                             service_name, created_by)
select ${q(MASTER_ID)}::uuid, s.id, p.client,
       ((b.today + p.day) + p.at) at time zone 'America/New_York',
       ((b.today + p.day) + p.at + make_interval(mins => s.duration_min)) at time zone 'America/New_York',
       ((b.today + p.day) + p.at + make_interval(mins => s.duration_min)) at time zone 'America/New_York',
       p.status, s.price, s.name, 'master'
  from plan p join public.services s on s.id = p.svc, base b;
`;

fs.writeFileSync(path.join(ROOT, 'supabase', 'seed.sql'), sql);
console.log('✓ supabase/seed.sql (owner: ' + ownerEmail + ')');
